using SimulationStorm.Collections.Presentation;
using SimulationStorm.Simulation.Statistics.Presentation.CommandExecutionStats.DataTypes;

namespace SimulationStorm.Simulation.Statistics.Presentation.CommandExecutionStats;

public class CommandExecutionStatsState : CollectionAndManagerStateBase<CommandExecutionResultRecord>;